name: Run black

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Filter python files
      run: |
        echo "files_added=`echo ${{ steps.file_changes.outputs.files_added }} | tr ' ' '\n' | grep .py | tr '\n' ' '`" >> $GITHUB_ENV
        echo "files_modified=`echo ${{ steps.file_changes.outputs.files_modified }} | tr ' ' '\n' | grep .py | tr '\n' ' '`" >> $GITHUB_ENV
        echo "action_state=yellow" >> $GITHUB_ENV
    - name: Run black
      run: |
        echo "$files_modified"
        echo "$files_added"
        echo $action_state
        black --check $files_added $files_modified __init__.py
